name: coffee_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  coffee_api_resources:
    path: ../coffee_api_resources
  dart_frog: ^1.0.0
  mysql_client: ^0.0.27

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
